### ISSUE TITLE
[FEATURE] Configure Spring Boot for project

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#22]
**Feature description**
Need to configure Spring Boot application using next tool: https://start.spring.io/
Project: `Maven`, language: `Java`, version: `2.7.5`, Group: `team.asd`, Artifact: `java-intern`, name: `intern-application`, package: `team.asd`

Next, you can download full project initialiser by pressing `GENERATE` button or view project structure with code with `EXPLORE` button

Move all dependencies, parent configuration, build plugin to your project's pom file
Copy `DemoApplication.java` file and `application.properties` resources to corresponding location in your project 

For more info please use next tutorial: https://spring.io/quickstart

**Expected result**
Run your test class (with `@SpringBootApplication`) without errors

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Project was configured with Spring Boot
