### ISSUE TITLE
[FEATURE] Implement CRUD methods for `party` table

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#27]
**Feature description**
Need to implement object Party, PartyDao and PartyService

Party class is the entity-object with fields (described [here](https://github.com/rdovgan/asd-java-intern/wiki/Database#party)), getters and setters. Location: `entity` package
PartyDao - is DB service layer to call MySQL queries. It should be an interface with declared methods for now. Location: `dao` package
In PartyService you need to implement next methods: `readById`, `create`, `update`, `delete`. Use methods from PartyDao if you need to call DB.  Location: `service` package

After PartyService implementation you need to implement tests for it.

**Requirements**
Project with configured SpringBoot

**Expected result**
Implemented PartyService with JUnit tests for it

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
CRUD methods for party table were implemented
