### ISSUE TITLE
[FEATURE] Create a controller for PartyService

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#28]
**Feature description**
Implement a controller for PartyService with next APIs:

> `GET` `/party/{id}` to get entity by ID

> `POST` `/party/` to create an entity

> `PUT` `/party/` for entity update

> `DELETE` `/party/{id}` to remove entity

Also, need to create a separate DTO object for Party entity (location: `dto` package) and ConverterUtil (location: `util` package) to convert PartyDto to Party object and vise versa

**Requirements**
Implemented PartyService

**Expected result**
All API for PartyService should work correctly

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Controller for PartyService was implemented.
