### ISSUE TITLE
[FEATURE] Implement CRUD methods for `channel_partner` table

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#38]
**Feature description**
Need to implement object ChannelPartner, ChannelPartnerDao and ChannelPartnerService

ChannelPartner class is the entity-object with fields (described [here](https://github.com/rdovgan/asd-java-intern/wiki/Database#channel_partner)), getters and setters.  Location: `entity` package
ChannelPartnerDao - is DB service layer to call MySQL queries. It should be an interface with declared methods for now.  Location: `dao` package
In ChannelPartnerService you need to implement next methods: `readById`, `create`, `update`, `delete`. Use methods from ChannelPartnerDao if you need to call DB.  Location: `service` package

After ChannelPartnerService implementation you need to implement tests for it.

**Requirements**
Project with configured SpringBoot

**Expected result**
Implemented ChannelPartnerService with JUnit tests for it

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Done. CRUD methods for `channel_partner` table were implemented.
