### ISSUE TITLE
[FEATURE] Create a controller for ChannelPartnerService

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#39]
**Feature description**
Implement a controller for ChannelPartnerService with next APIs:

> `GET` `/channel_partner/{id}` to get entity by ID

> `POST` `/channel_partner/` to create an entity

> `PUT` `/channel_partner/` for entity update

> `DELETE` `/channel_partner/{id}` to remove entity

Also, need to create a separate DTO object for ChannelPartner entity (location: `dto` package) and ConverterUtil (location: `util` package) to convert ChannelPartnerDto to ChannelPartner object and vise versa

**Requirements**
Implemented ChannelPartnerService

**Expected result**
All API for ChannelPartnerService should work correctly

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Done. Controller for ChannelPartnerService was implemented
