### ISSUE TITLE
[FEATURE] Implement CRUD methods for `property_manager_info` table

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#43]
**Feature description**
Need to implement object PropertyManagerInfo, PropertyManagerInfoDao and PropertyManagerInfoService

PropertyManagerInfo class is the entity-object with fields (described [here](https://github.com/rdovgan/asd-java-intern/wiki/Database#property_manager_info)), getters and setters.  Location: `entity` package
PropertyManagerInfoDao - is DB service layer to call MySQL queries. It should be an interface with declared methods for now.  Location: `dao` package
In PropertyManagerInfoService you need to implement next methods: `readById`, `create`, `update`, `delete`. Use methods from PropertyManagerInfoDao if you need to call DB.  Location: `service` package

After PropertyManagerInfoService implementation you need to implement tests for it.

**Requirements**
Project with configured SpringBoot

**Expected result**
Implemented PropertyManagerInfoService with JUnit tests for it

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
CRUD methods for property_manager_info were imlemented
