### ISSUE TITLE
[FEATURE] Create a controller for `PropertyManagerInfoService`

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#45]
**Feature description**
Implement a controller for PropertyManagerInfoService with next APIs:

> `GET` `/property_manager_info/{id}` to get entity by ID

> `POST` `/property_manager_info/` to create an entity

> `PUT` `/property_manager_info/` for entity update

> `DELETE` `/property_manager_info/{id}` to remove entity

Also, need to create a separate DTO object for PropertyManagerInfo entity (location: `dto` package) and ConverterUtil (location: `util` package) to convert PropertyManagerInfoDto to PropertyManagerInfo object and vise versa

**Requirements**
Implemented PropertyManagerInfoService

**Expected result**
All API for PropertyManagerInfoService should work correctly

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Controller for PropertyManagerInfoService was implemented
