### ISSUE TITLE
[FEATURE] Implement DB layer for `manager_to_channel` table

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#50]
**Feature description**
Need to implement ManagerToChannelDao service and connect DB to methods
All SQL queries should be implemented in `ManagerToChannelMapper.xml`. Also, need to create the same methods in `ManagerToChannelMapper` interface with correct parameters. `ManagerToChannelDao` service should use mappers and operate with session

**Requirements**
Created `manager_to_channel` table in `asd_db` scheme

**Expected result**
Implemented ManagerToChannelDao service with CRUD methods and with relation to DB

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Done. DB layer for `manager_to_channel `table was implemented
