### ISSUE TITLE
[FEATURE] Implement additional methods

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#54]
**Feature description**
Need to implement methods and APIs with next functionality:
1) Retrieve and filter all Party records by next parameters: `userType`, `name`, `state`
2) Retrieve and filter all Party records by next parameters: `emailAddress`, `userType`, `state`, `name`
3) Retrieve a list of ChannelPartner items by `abbreviation` parameter mask
4) Retrieve one ChannelPartner record by next parameters: `partyId`, `state`
5) Retrieve one PropertyManagerInfo record by `pmId` and `state` parameters
6) Retrieve one ManagerToChannel record by `propertyManagerId` and `channelPartnerId` parameters
7) Retrieve all ManagerToChannel records by `channelPartnerId` parameter with `netRate` filter
8) Store a list of ManagerToChannel records

**Requirements**
Implemented CRUD methods for services, controllers and MyBatis methods

**Expected result**
Implemented API endpoints in controller, service methods and MyBatis methods

**Need to create a new working branch from `master` repository** ⬅️ ❗️

**Comment by rdovgan** [comment]
@olena-syrotenko please discuss all questions related to this task here in comments

**Comment by olena-syrotenko** [comment]
Should the first and second methods be separate or it can be implemented with `@RequestParam`?

**Comment by rdovgan** [comment]
@olena-syrotenko for each task should be a separate method

**Comment by rdovgan** [comment]
@olena-syrotenko
there are some notes for your tasks:
1. `name` parameter is required
2. `emailAddress` parameter is required
3.  At least one character is required in parameter
5. `pmId` parameter is required. If you get more than one record, please select last (by ID)
6. At least one parameter should not be `null`
7.  `channelPartnerId` is required

All other parameters can be null and in this case you should not filter by this parameter

**Comment by olena-syrotenko** [comment]
@rdovgan Should I implement service and controller for ManagerToChannel?

**Comment by rdovgan** [comment]
> @rdovgan Should I implement service and controller for ManagerToChannel?

@olena-syrotenko No, it should be integrated into existing services. Let's put them into ChannelPartner service and controller

**Comment by olena-syrotenko** [comment]
Done. Additional methods were implemented
