### ISSUE TITLE
[FEATURE] Add Swagger support

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#57]
**Feature description**

1. Add swagger dependency to project
2. Add swagger annotations to controllers, DTOs and API methods
3. Check documentation by next API: `localhost:8080/swagger-ui/index.html`

Tutorials:
https://www.javainuse.com/spring/boot_swagger
https://www.baeldung.com/swagger-set-example-description

Documentation:
https://swagger.io/tools/open-source/open-source-integrations/

**Requirements**
All endpoint should be described with Swagger annotations

**Expected result**
Generated documentation for each 

**You can use existing working branch or checkout from `master`**

**Comment by olena-syrotenko** [comment]
Done. Swagger support was added to the project ans endpoints were described using annotations
