### ISSUE TITLE
[FEATURE] Implement methods using JOINs 

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#59]
**Feature description**
Need to implement next functionality:

1. Implement method for PartyService. Need to retrieve Party items with next conditions: 
- method parameters: `mask` and `userType`
- join `party` with `channel_partner` table
- ChannelPartner's name items should starts with provided `mask` parameter
- filter Party items by `userType` parameter
- Party items should be with `Created` or `Suspended` state

2. Implement method for ChannelPartnerService. Need to retrieve ManagerToChannel items with next conditions: 
- join `manager_to_channel` with `channel_partner` and `property_manager_info` tables
- ChannelPartner items should be with `Suspended` or `Initial` state
- PropertyManagerInfo items should be with `Suspended` or `Initial` state
- method parameters: `fundsHolder` (to filter ChannelPartner and PropertyManagerInfo items by this parameter)

**Requirements**
Need to use SQL JOIN for implementation

**Comment by olena-syrotenko** [comment]
@rdovgan should I check parameter `funds_holder` in `manager_to_channel` record or in both  `channel_partner` and `property_manager_info` records in method for getting ManagerToChannel items by fundsHolder?

**Comment by olena-syrotenko** [comment]
Done. Additional methods with JOINs were implemented.
