### ISSUE TITLE
[FEATURE] Implement Party report

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#63]
**Feature description**
1. Create a new controller. Methods should be implemented in PartyService, PartyDao and PartyMapper accordingly
2. Implement a method to retrieve a Party info by `partyId` from DB
3. Response should contains next items:
- PartyDTO
- ChannelPartner data (if exists) with `Created` state with next data: `abbreviation`, `channelName`, `commission`, `fundsHolder`
- PropertyManager data (if exists) with `Created` state with next data: `fundsHolder`, `paymentAmount`, `paymentType`, `commission`
- List of ManagerToChannel connections. Retrieve items by `channel_partner_id` if `party.user_type` is `ChannelPartner` or by `property_manager_id` if `party.user_type` is `PropertyManager`

**Expected result**
Deployed feature to a Virtual Server with described endpoint

**Need to create a new working branch from `master` repository**

**Comment by olena-syrotenko** [comment]
Done. Method to retrieve a Party report was implemented.
