### ISSUE TITLE
[FEATURE] Add pagination to party report (Optional)

### ISSUE THREAD

**Issue by DenisTymchuk** [olena-syrotenko/asd-java-intern#66]
**Feature description**
Need to add two new parameters to the party report API
- page
- itemsPerPage

And implement pagination in mybatis query

**Expected result**
Response based on input parameters. For example: if page = 3 and itemsPerPage = 5, you should return five elements (from 10 to 15) in DB

**Comment by olena-syrotenko** [comment]
Done. Method for pagination party reports was implemented
