### ISSUE TITLE
[FEATURE] Deploy DB layer to Nexus

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#70]
**Feature description**
1. Configure Nexus storage for your project. Import `data/nexus-settings.xml` as Maven configuration
2. Deploy your `party-layer` module to Nexus (run `deploy` job on Maven panel)
3. Check if it was deployed to Nexus storage by next URL: http://51.89.6.109:8081/#browse/browse:maven-snapshots

**Comment by olena-syrotenko** [comment]
Done. `party-layer` module was deployed to Nexus
![image](https://user-images.githubusercontent.com/104794400/209533119-e76a2481-b450-4797-921e-e9375d28b88c.png)
