### ISSUE TITLE
[FEATURE] Implement a method using other DB layers

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#71]
**Feature description**
Implement a method and API to retrieve user-readable information by party ID. Response should contain next fields:
```
  partyId
  partyName
  numberOfPayment
  commissionAmount
  productsCountBySupplier
  paymentTransactionCountByPartner
```

**Requirements**
Check Nexus repository for `transaction-layer` and `product-layer` dependencies

**Comment by olena-syrotenko** [comment]
@rdovgan are `numberOfPayment` and  `commissionAmount` related to `property_manager_info` table?
