### ISSUE TITLE
[FEATURE] Create a redis module

### ISSUE THREAD

**Issue by rdovgan** [olena-syrotenko/asd-java-intern#73]
**Feature description**
1. Need to create a separate module
2. Create a resource pool using Jedis client to connect to Redis server. Please use next documentation: https://github.com/redis/jedis
3. Use next credentials for accessing Redis server: host - `51.89.6.109`, port - `6379`, password - `testP@ssword`. Put these credentials into properties file
4. Implement RedisClient service. It should use Redis resource pool manager you implemented before to access Redis server. Next methods should be implemented: `readByKey(String key)`, `saveValueByKey(String key, String value)`, `saveList(String keyList, List list)`, `saveElementIntoList(String keyList, String value)`, `retrieveList(String keyList)`, `saveValueInHashMap(String primaryKey, String secondaryKey, String value)`, `retrieveValueFromHashMap(String primaryKey, String secondaryKey)`, `retrieveValueFromHashMap(String primaryKey)`, `saveValueWithExpireDate(String key, String value, long expireDate)`
5. Connect redis module to your application
6. Implement a controller with methods to store/retrieve elements to/from redis by key

**Requirements**
Read next Redis documentations: 
https://redis.io/docs/data-types/
https://redis.io/docs/manual/

Before starting the implementation, try to connect to Redis server from your console:
1. Install `redis-cli`: https://redis.io/docs/getting-started/
2. Connect to Redis server: `redis-cli -h 51.89.6.109 -p 6379 -a 'testP@ssword'`
3. Check connection: enter `ping` command -> expected response: `PONG`
7. Get the list of all keys: `keys *`
8. Put a value for a key: `set your_key your_value`
9. Retrieve a value by the specified key: `get your_key`

**Comment by olena-syrotenko** [comment]
Done. Redis module was implemented
